### ISSUE TITLE
Is there a way to replicate the paper results?

### ISSUE THREAD

**Issue by thommo9933** [onnokleen/mfGARCH#17]
I've been trying to replicate the results given in "Two are better than one: Volatility forecasting using
multiplicative component GARCH-MIDAS models". 

It looks like the data available in the R package is the same as that used in the empirical examples in the paper, but I am unable to replicate the results of Table 4.

**Comment by onnokleen** [comment]
I only tried replicating the NFCI and NAI results right now but for me everything seems largely in line. I updated the package since the release of the paper and made some optimisations here and there. That might lead to the numbers not 100% aligning. This mostly applies to the weighting parameters because they are relatively hard to estimate.

**Comment by thommo9933** [comment]
Yes, it was the weight parameters I was getting stuck on.  And, yes, they do seem hard to pin down.  Appreciate.
